<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['print_server_app_description'] = 'Приложение "Сервер печати" предоставляет общий интерфейс для печати на принтерах в сети. Это позволяет клиентам в локальной сети, печатать на общих принтерах, что упрощает администрирование службы печати в сети.';
$lang['print_server_app_name'] = 'Продвинутый сервер печати';
$lang['print_server_go_to_management_tool'] = 'Перейти к инструменту управления сервером печати';
$lang['print_server_management_tool'] = 'Cредство управления серверами печати';
$lang['print_server_management_tool_help'] = 'Перейти по ссылке, чтобы получить доступ к инструменту управления сервером печати.';
$lang['print_server_management_tool_not_accessible'] = 'Средство управления сервером печати не доступна, если сервер не работает';
