<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['print_server_app_description'] = 'The Advanced Print Server app provides a common print interface to printers on the network.  This allows clients on the LAN to share print resources and eases administration into one centralized service.';
$lang['print_server_app_name'] = 'Продвинутый сервер печати';
$lang['print_server_go_to_management_tool'] = 'Перейти к инструменту управления сервером печати';
$lang['print_server_management_tool'] = 'Cредство управления серверами печати';
$lang['print_server_management_tool_help'] = 'Перейти по ссылке, чтобы получить доступ к инструменту управления сервером печати.';
$lang['print_server_management_tool_not_accessible'] = 'Средство управления сервером печати не доступна, если сервер не работает';
