#!/bin/sh

[ -x /usr/clearos/apps/print_server/deploy/syncaction ] && /usr/clearos/apps/print_server/deploy/syncaction

# Set default start/boot
#-----------------------

logger -p local6.notice -t installer "app-print-server-core - enabling CUPS print server"
chkconfig cups on >/dev/null 2>&1

logger -p local6.notice -t installer "app-print-server-core - starting CUPS print server"
service cups start >/dev/null 2>&1
