#!/bin/sh

TIMESTAMP=`date "+%b-%d-%Y-%T"`

# CUPS configuration
#-------------------

CHECK=`grep cupsd.policy.conf /etc/cups/cupsd.conf 2>/dev/null`

if [ -z "$CHECK" ]; then
    logger -p local6.notice -t installer "app-print-server-core - setting default configuration"
    [ -e /etc/cups/cupsd.conf ] && mv /etc/cups/cupsd.conf /var/clearos/print_server/backup/cupsd.conf.$TIMESTAMP
    cp /usr/clearos/apps/print_server/deploy/cupsd.conf /etc/cups/cupsd.conf
    chown root.lp /etc/cups/cupsd.conf
    chmod 640 /etc/cups/cupsd.conf
fi

# Grab bootstrap certificates from Certificate Manager
#-----------------------------------------------------

KEY_SOURCE=/etc/pki/CA/bootstrap.key
KEY=/etc/cups/ssl/server.key

if [ ! -s "$KEY" ]; then
    logger -p local6.notice -t installer "app-print-server-core - prepping server key"
    cp $KEY_SOURCE $KEY
    chown root.lp $KEY
    chmod 640 $KEY
fi

CRT_SOURCE=/etc/pki/CA/bootstrap.crt
CRT=/etc/cups/ssl/server.crt

if [ ! -s "$CRT" ]; then
    logger -p local6.notice -t installer "app-print-server-core - prepping server certificate"
    cp $CRT_SOURCE $CRT
    chown root.lp $CRT
    chmod 640 $CRT
fi

# Update print server configuration based on network info
#--------------------------------------------------------

/var/clearos/events/network_configuration/print_server
