<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['print_server_app_description'] = 'The Advanced Print Server app provides a common print interface to printers on the network.  This allows clients on the LAN to share print resources and eases administration into one centralized service.';
$lang['print_server_app_name'] = 'Zaawansowany serwer wydruku';
$lang['print_server_go_to_management_tool'] = 'Przejdź do narzędzia zarządzającego serwerem wydruku';
$lang['print_server_management_tool'] = 'Narzędzie do zarządzania serwerem wydruku';
$lang['print_server_management_tool_help'] = 'Kliknij w link aby uruchomić narzędzie do zarządzania serwerem wydruku.';
$lang['print_server_management_tool_not_accessible'] = 'Narzędzie do zarządzania serwerem wydruku nie jest dostępne kiedy serwer nie jest uruchomiony';
