<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['print_server_app_description'] = 'The Advanced Print Server app provides a common print interface to printers on the network.  This allows clients on the LAN to share print resources and eases administration into one centralized service.';
$lang['print_server_app_name'] = 'Advanced Print Server';
$lang['print_server_go_to_management_tool'] = 'Go to Print Server Management Tool';
$lang['print_server_management_tool'] = 'Print Server Management Tool';
$lang['print_server_management_tool_help'] = 'Follow the link to access the Print Server management tool.';
$lang['print_server_management_tool_not_accessible'] = 'The Print Server management tool is not available when the server is not running';
